import type {NextPage} from "next";
import {GetServerSideProps} from 'next';
import Head from 'next/head';

import {Navbar} from '../components/navarbar';
import {OutfitCard} from '../components/outfitcard';
import styles from '../styles/Home.module.css';
import {Outfit} from './api/types';

type Props = {
  data: Outfit[] | null;
  cookie: string;
  error: string | null;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  let props: Props = {
    data: null,
    cookie: "",
    error: null,
  };

  let cookie = context.req.cookies["rys_user_id"];
  props.cookie = cookie ? cookie : ""

  await fetch("http://localhost:8000/outfits")
    .then((response) => {
      if (!response.ok) {
        throw new Error("response not ok");
      }

      return response.json();
    })
    .then((data: Outfit[]) => {
      props.data = data
    })
    .catch((err: Error) => {
      props.error = err.message
    });

  if (props.error) {
    return {props}
  }

  return {props};
};

function Home({data, cookie, error}: Props) {

  if (error) {
    return <div className={styles.container}>Error {error}</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rate Their Style</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <Navbar  cookie={cookie}  />
        </header>
        <section>
          <h1>Welcome to Rate Your Style</h1>
          <p>
            Creating a fashion database ranging from everyday wear worn by
            fashion enthusiasts, to outfits worn by celebrities/influencers, to
            looks model-ed on the runway. Use the database to find inspo, read
            reviews, and upload your own outfit reviews.
          </p>
        </section>
        <section>
          <h1>Featured</h1>
          {data && data.map((item) => <OutfitCard data={item} key={item.id} />)}
        </section>
      </main>
    </div>
  );
}

export default Home;
