import type { NextPage } from "next";
import Head from 'next/head';
import useSWR from 'swr';

import { Navbar } from '../components/navarbar';
import styles from '../styles/Home.module.css';
import { Outfit, ResponseError } from './api/types';
import { GetServerSideProps } from "next";
import { OutfitCard } from "../components/outfitcard";


type Props = {
  data: Outfit[] | null;
  error: Error | null;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  let props: Props = {
    data: null,
    error: null,
  };

  let cookie = context.req.cookies['rys_user_id'];
  if (!cookie) {
    let resp = await fetch("http://localhost:8000/cookie").then(response => {
      console.log("this is repsonse")
      console.log(response)
      if (response.ok) {
        return null
      }

      return Error("cookie not set")
    })

    context.res.setHeader('set-cookie', ['rys_user_id=test'])

    if (resp === null) {
      console.log("good")
    }
  }

  let resp = await fetch("http://localhost:8000/outfits")
    .then((response) => {

      if (!response.ok) {
        throw new Error("response not ok")
      }

      return response.json()
    })
    .then((data: Outfit[]) => {

      return data

    }).catch((err) => {
      return err
    })

  props.data = resp

  return { props };
};

function Home({
  data,
  error,
}: Props) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Rate Their Style</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <Navbar />
        </header>
        <section>
          <h1>Welcome to Rate Your Style</h1>
          <p>
            Creating a fashion database ranging from everyday wear worn by fashion enthusiasts, to outfits worn by celebrities/influencers, to looks model-ed on the runway.
            Use the database to find inspo, read reviews,
            and upload your own outfit reviews.
          </p>
        </section>
        <section>
          <h1>Featured</h1>
          {data && data.map((item) => (
            <OutfitCard data={item} key={item.id} />
          ))}
        </section>
      </main>
    </div>
  );
};

export default Home;
