import type {NextPage} from "next";
import Head from 'next/head';
import useSWR from 'swr';

import {Navbar} from '../components/navarbar';
import styles from '../styles/Home.module.css';
import {Outfit, ResponseError} from './api/types';

const fetcher = async (url: string) => {
  const res = await fetch(url);
  const data = await res.json();

  if (res.status !== 200) {
    throw new Error(data.message);
  }
  return data;
};

function FeaturedSection(props: {data: Outfit}) {
  return (
    <div className="w-fit shadow-md p-4 bg-off-white rounded-md my-2 max-h-card overflow-auto">
      <div className="grid grid-cols-5 gap-4 object-contain">
        {/* <div className="col-span-2 max-h-20"> */}
        {/* <ChevronLeftIcon /> */}
        <img className="col-span-1 object-contain" src={props.data.picture_urls[0]} />
        {/* <ChevronRightIcon /> */}
        {/* </div> */}

        <div className="col-span-2 bg-white p-2 rounded-md">

          <h6>
            {props.data.title} <br />
            date: {props.data.date} <br />
            modeled by: {props.data.model}
          </h6>
          <div className="mt-4">
            {props.data.description}
          </div>

          <div className="mt-4">
            <div>Audience score:</div>
            <div className="px-2 py-2.5 border border-black inline-block rounded-full">
              {props.data.audience_rating}
            </div>
            <div className="mx-2 inline-block">
              {props.data.audience_rating_count} ratings submitted
            </div>
          </div>

        </div>
        <div className="col-span-2 bg-white p-2 rounded-md">
          <h6>Breakdown</h6>
          <ul className="">
            {props.data.items.map((item) => (
              <li className="mt-3">
                {item.description}
                <br />
                {item.brand}
                <br />
                {item.price}
                <div>
                  <div className="px-2 py-2 border inline-block rounded-full">
                    {item.rating}/5
                  </div>
                  <div className="mx-2 inline-block">
                    {item.review}
                  </div>

                </div>
              </li>
            ))}
          </ul>

        </div>
      </div>
    </div>
  );
}

const Home: NextPage = () => {
  const {data, error, isLoading, isValidating} = useSWR<
    Outfit[],
    ResponseError
  >(`/api/featured_lists`, fetcher);

  if (error) return <div>{error.message}</div>;
  if (isLoading) return <div>Loading...</div>;
  if (!data) return null;

  return (
    <div className={styles.container}>
      <Head>
        <title>Rate Their Style</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <Navbar />
        </header>
        <section>
          <h1>Welcome to Rate Your Style</h1>
          <p>
            We are creating a fashion database ranging from looks model-ed on
            the runway to fits worn by celebrities to everyday wear worn by
            fashion enthuisiasts. Use the database to find inspo, read reviews,
            and upload your own outfit reviews.
          </p>
        </section>
        <section>
          <h1>Featured</h1>
          {data.map((item) => (
            <FeaturedSection data={item} />
          ))}
        </section>
      </main>
    </div>
  );
};

export default Home;
